# Ignored files or directories
AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"

# Changed default format
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Disabled
Style/Documentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

# Disabled for RSpec
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
