---
openapi: 3.0.3
info:
  title: API V1
  version: v1
paths:
  # Authentication
  /api/v1/login:
    $ref: paths/sessions.yaml#login

  # Admin/User
  /api/v1/admin/users/{id}:
    $ref: paths/admin/users.yaml#show

  # HealthChecks
  /api/v1/ping:
    $ref: paths/health_checks.yaml#ping
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
