---
openapi: 3.0.3
info:
  title: API V1
  version: v1
paths:
  /api/v1/admin/users/{id}:
    $ref: paths/admin/users.yaml#show
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
