DATABASE_HOST:
DATABASE_USERNAME:
DATABASE_PASSWORD:
DATABASE_NAME:

SECRET_KEY_BASE:

SERVER_HOST:

GOOGLE_API_KEY:
GOOGLE_APPLICATION_CREDENTIALS:

REDIS_URL:

# Sendgrid
SENDGRID_API_KEY:

SMTP_ADDRESS:
SMTP_PORT:
SMTP_DOMAIN:
SMTP_USER_NAME:

DEFAULT_EMAIL_FROM:

#Kafka
KAFKA_BROKERS:
KAFKA_CLIENT_ID:
